nombre_p1=input("ingrese el nombre del paciente: ")
peso1=input("Ingrese el peso del paciente: ")
estatura1=float(input("Ingrese la estatura del paciente: "))
edad1=int(input("Ingrese la edad del paciente: "))
nombre_p2=input("Ingrese el nombre del paciente: ")
peso2=input("Ingrese el peso del paciente: ")
estatura2=float(input("Ingrese la estatura del paciente: "))
edad2=int(input("Ingrese la edad del paciente: "))
nombre_p3=input("Ingrese el nombre del paciente: ")
peso3=input("Ingrese el peso del paciente: ")
estatura3=float(input("Ingrese la estatura del paciente: "))
edad3=int(input("Ingrese la edad del paciente: "))
paciente1=(nombre_p1+peso1+str(estatura1)+str(edad1))
paciente2=(nombre_p2+peso2+str(estatura2)+str(edad2))
paciente3=(nombre_p3+peso3+str(estatura3)+str(edad3))
print(paciente1)
print(paciente2)
print(paciente3)
